### ISSUE TITLE
error, help

### ISSUE THREAD

**Issue by areejayy** [Angarsk8/extract-metadata#1]
can you tell me what am i doing wrong? its giving me error
Error: Internal server error [500]
do i have to copy the code in the server folder?

```
        // here is my code.
        var url = event.target.url.value;
        var title,description;
        Meteor.call('fetchMetadata', url, function (error, result) {
            //Error is empty if all goes well
            //Result will containt and object like:
             //{name:'Page name',description:'Here's the metadata description',image:'img url'}
             if (error){
                console.log("error occurred while fetching"+error);
             }
             else{
                title=name;
                description=description;
             }
        });
        //var title = event.target.title.value;
        //var description = event.target.description.value;
        console.log("The url they entered is: "+url);

        //  put your website saving code in here!   

        if(Meteor.user()){
            Websites.insert({
                url:url,
                title:title,
                description:description,
                createdBy:Meteor.user()._id,
                createdOn:new Date(),
                vote:0
            });
        }
```

**Comment by Angarsk8** [comment]
Hi @areejayy, 

Can you show me the stack trace that appears in the meteor console when this error happens?

I think I know the reason of this error. The `extract-metadata` package just adds a server side method that you can use in your application to crawl the metadata data of a given website's url. Every server side method must validate the data that comes from the client! Since the `extract-metadata` package uses the optional core package `check` to "check" the arguments in a server side method call, all you have to do is to add that package. Just type `$ meteor add check` and everything should be working properly. 

I hope that works,

**_Andrés Alejandro García Hurtado**_

**Comment by Angarsk8** [comment]
@areejayy Did it work for you?
